export const REQUEST_GET_PROFILE = 'REQUEST_GET_PROFILE';
export const SUCCESS_GET_PROFILE = 'SUCCESS_GET_PROFILE';
export const ERROR_GET_PROFILE = 'ERROR_GET_PROFILE';
export const REQUEST_EDIT_PROFILE = 'REQUEST_EDIT_PROFILE';
export const SUCCESS_EDIT_PROFILE = 'SUCCESS_EDIT_PROFILE';
export const ERROR_EDIT_PROFILE = 'ERROR_EDIT_PROFILE';
