export const REQUEST_GET_CONTINUE_WATCHING = 'REQUEST_CONTINUE_WATCHING';
export const SUCCESS_CONTINUE_WATCHING = 'SUCCESS_CONTINUE_WATCHING';
export const ERROR_CONTINUE_WATCHING = 'ERROR_CONTINUE_WATCHING';
